/**
 * Дефолтный каталог (4 юрты + 6 аксессуаров) для отображения, если в БД ещё нет данных.
 */

export const DEFAULT_YURTS = [
  { id: 'default-intimate', name: 'Kazakh 6-Kanat', slug: 'intimate', diameter_m: 5, kanat: 6, capacity_min: 15, capacity_max: 20, price_usd: 5000, price_usd_max: 8000, rental_price_usd: 1000, production_days_min: 30, production_days_max: 45, description: 'Traditional Kazakh 6-kanat yurt. 5x5 m, height 3.6 m, weight ~600 kg. Ideal for private retreats and intimate gatherings of 15-20 people.', history: 'The 6-kanat yurt is the classic compact form of the Kazakh nomadic dwelling. Built by hand using techniques passed down through generations, it offers the perfect balance of portability and comfort.', photos: null, supplier_id: undefined },
  { id: 'default-cozy', name: 'Kazakh 8-Kanat', slug: 'cozy', diameter_m: 6, kanat: 8, capacity_min: 25, capacity_max: 30, price_usd: 6000, price_usd_max: 10000, rental_price_usd: 1000, production_days_min: 35, production_days_max: 50, description: 'Traditional Kazakh 8-kanat yurt. 6x6 m, height 4 m, weight ~700 kg. Perfect for family events and glamping with 25-30 guests.', history: 'The 8-kanat yurt has long been the choice for extended families and small celebrations on the steppe. Its proportions balance warmth in winter and airflow in summer.', photos: null, supplier_id: undefined },
  { id: 'default-classic', name: 'Kazakh 12-Kanat', slug: 'classic', diameter_m: 8, kanat: 12, capacity_min: 35, capacity_max: 55, price_usd: 14000, price_usd_max: 20000, rental_price_usd: 1500, production_days_min: 40, production_days_max: 55, description: 'Traditional Kazakh 12-kanat yurt. 8x8 m, height 4.7 m, weight ~800 kg. Our most popular model for events and lodges hosting 35-55 people.', history: 'The 12-kanat yurt is the classic format used for gatherings, ceremonies and hospitality across Central Asia.', photos: null, supplier_id: undefined },
  { id: 'default-spacious', name: 'Kazakh 16-Kanat', slug: 'spacious', diameter_m: 9, kanat: 16, capacity_min: 60, capacity_max: 80, price_usd: 17000, price_usd_max: 25000, rental_price_usd: 2000, production_days_min: 45, production_days_max: 60, description: 'Traditional Kazakh 16-kanat yurt. 9x9 m, height 4.8 m, weight ~1500 kg. Ideal for large events hosting 60-80 people.', history: 'The 16-kanat model is the pinnacle of the traditional Kazakh yurt: a grand space for weddings, festivals and corporate events.', photos: null, supplier_id: undefined },
] as const

export const DEFAULT_ACCESSORIES = [
  { id: 'default-felt-carpet', name: 'Felt carpet', slug: 'felt-carpet', category: 'carpet' as const, description: 'Handmade felt carpet for yurt floor. Natural wool, traditional patterns. Various sizes on request.', history: 'Felt carpets have lined yurt floors for millennia. Ours are made from natural wool using traditional pressing and patterning techniques, bringing warmth and heritage into every space.', price_usd: 450, price_kzt: 230000, stock_quantity: 0, photos: null, supplier_id: undefined, name_i18n: null },
  { id: 'default-low-table', name: 'Low table', slug: 'low-table', category: 'furniture' as const, description: 'Traditional low wooden table for yurt interior. Fits 4-6 people.', history: 'The low table is the centre of life inside the yurt: meals, tea and conversation happen around it. Our tables are made from solid wood by craftspeople who have built them for generations.', price_usd: 380, price_kzt: 195000, stock_quantity: 0, photos: null, supplier_id: undefined, name_i18n: null },
  { id: 'default-stools-set', name: 'Stools set', slug: 'stools-set', category: 'furniture' as const, description: 'Set of 4 wooden stools for yurt. Compact and stackable.', history: 'Stools in the yurt are traditionally used for seating around the low table. Our set of four is designed to stack and store easily, following the same compact logic of nomadic furniture.', price_usd: 320, price_kzt: 165000, stock_quantity: 0, photos: null, supplier_id: undefined, name_i18n: null },
  { id: 'default-white-cover', name: 'White cover', slug: 'white-cover', category: 'cover' as const, description: 'White outer cover for yurt. Weather-resistant, custom size to order. Production 1 month.', history: 'The outer cover protects the yurt from rain and wind. White canvas has long been used for its reflectivity and clean look. We make each cover to measure for your structure.', price_usd: null, price_kzt: 1000000, stock_quantity: 0, photos: null, supplier_id: undefined, name_i18n: null },
  { id: 'default-silver-cover', name: 'Silver cover', slug: 'silver-cover', category: 'cover' as const, description: 'Silver-grey outer cover for yurt. Weather-resistant, custom size to order. Production 1 month.', history: 'Silver and grey covers offer a modern, neutral look while protecting the yurt from rain and sun. Made to measure for your structure.', price_usd: null, price_kzt: 1000000, stock_quantity: 0, photos: null, supplier_id: undefined, name_i18n: null },
  { id: 'default-transparent-cover', name: 'Transparent cover', slug: 'transparent-cover', category: 'cover' as const, description: 'Transparent PVC cover for yurt. Lets light in, protects from rain. Custom order, 1 month production.', history: 'Transparent covers are a modern take on the traditional yurt: they keep the round shape and shelter while bringing in natural light. Ideal for daytime use and events in any season.', price_usd: null, price_kzt: 1000000, stock_quantity: 0, photos: null, supplier_id: undefined, name_i18n: null },
  { id: 'default-furniture-set', name: 'Furniture set', slug: 'furniture-set', category: 'furniture' as const, description: 'Complete yurt interior: low table, stools, felt carpets. Custom configuration on request.', history: 'A full interior set brings the yurt to life: table, stools and felt together. This combination has been used for centuries and is still the standard for a complete, authentic yurt interior.', price_usd: 1200, price_kzt: 610000, stock_quantity: 0, photos: null, supplier_id: undefined, name_i18n: null },
] as const
